#########################################
# Set up and common commands & packages #
#########################################

# Checks that relevant packages (**not** imports!) are available and if so loads them in the workspace
if (!isTRUE(requireNamespace("icons", quietly = TRUE))) {
  stop("You need to install the packages 'icons'. Please run in your R terminal:\n remotes::install_github('mitchelloharawild/icons')")
}
# If 'icons' is installed but not loaded then attach the Namespace (so that all the relevant functions are available)
if (isTRUE(requireNamespace("icons", quietly = TRUE))) {
  if (!is.element("icons", (.packages()))) {
    attachNamespace("icons")
  }
}

# Sets default fonts for tikz
library(tikzDevice)
options(tikzLatexPackages=c(getOption("tikzLatexPackages"),"\\usepackage{inconsolata,}",
                            "\\usepackage[scaled=.89]{helvet}\n\\renewcommand{\\familydefault}{\\sfdefault}\n"))

# Trick to automatically convert pdf graphs generated with dev='tikz' into png so they work in html format
# see: https://github.com/rstudio/bookdown/issues/275
# NB: Need to specify 'density=600' in 'image_read' to get same quality as tikz
knitr::opts_hooks$set(dev = function(options) {
  if (identical(options$dev, 'tikz') && !knitr:::is_latex_output()) {
    options$fig.process = function(x) {
      if (!grepl('[.]pdf$', x)) return(x)
      x2 = sub('pdf$', 'png', x)
      magick::image_write(magick::image_read(x,density=600), x2, format = 'png', quality=90, density=600)
      x2
    }
  }
  options
})

# This is a hack to insert 'alt-text' in images created by the R chunks
# source: https://ropensci.org/technotes/2020/04/23/rmd-learnings/
# NB: the 'alt-text' needs to be **'title'** attribute that gets included in the list 'opts'
# which is included as part of the set up in the chunk, for example
#    ```{r echo=FALSE,opts=list(title="Alt-text",width="45%"...)}
# (see: https://www.computerhope.com/issues/ch001076.htm).
# Also, needs to specify the 'width' option (= what would normally be 'out.width') to ensure
# that the resulting HTML code to format the graph
knitr::knit_hooks$set(
  plot = function(x, options) {
    opts <- options$opts
    paste0(
      "<img src=",
      '"', x, '" ',
      if (!is.null(opts)) {
        # Here include the styling for the graphs - this ensure it's centered
        paste('style="display: block; margin: auto;"',
              # And this "glues" the options passed by the user (including the 'alt-text')
              glue::glue_collapse(glue::glue('{names(opts)}="{opts}"'),sep = " ")
        )
      },
      ">\n"
    )
  },
  # This sets up a switch that allows to automatically crop the images generated by R
  # https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html
  knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)
)

# Defaults for figure size
# fig.retina=3 improves the quality of the resulting graph (https://arm.rbind.io/slides/xaringan.html#89)
knitr::opts_chunk$set(fig.width=10, fig.height=9, out.width="55%", fig.align='center', fig.retina=3, crop=TRUE,
                      comment=NA,message=FALSE,error=FALSE)



# This sets up the figure path so that all the R-generated images are stored under 'img'
knitr::opts_chunk$set(fig.path="./img/")


# This allows to embed websites in the presentation
options(htmltools.dir.version = FALSE, htmltools.preserve.raw = FALSE)
# Then need to do
# ```{r, echo=FALSE, out.width="100%",out.extra='style="border: none;"'}
# knitr::include_url("URL here", height="80%")
# ```

# Table/knitr-related options
library(knitr)
library(kableExtra)
options(htmltools.dir.version = FALSE)
options(knitr.table.format = "html")
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# This defines how the code is formatted
knitr::opts_chunk$set(
  prompt = TRUE,
  highlight = TRUE,
  #background = '#FFFFFF',
  concordance=TRUE
)

# Relevant packages (to load globally - not for a single slide)
library(dplyr)
library(ggplot2)
library(xaringanExtra)
library(slides)

# Citations & Bibliography (https://github.com/yihui/xaringan/wiki/Bibliography-and-citations)
# RefManageR: https://arxiv.org/pdf/1403.2036v1.pdf
library(RefManageR)
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           style = "markdown",
           cite.style = "authoryear",
           super = FALSE,
           hyperlink = FALSE,
           dashed = FALSE
#           bibpunct = c("(",")","(",")",";",","),
)


# Formats the date in the title-slide
# If the date is specified as a string (to a specific value), then used that, else use current date
if(!is.null(rmarkdown::metadata$params$date)){date=rmarkdown::metadata$params$date} else {date=format(Sys.Date(),"%e %B %Y")}

# Also creates a variable 'short_date' that can be used in the footers
short_date=format(as.Date(date,format="%e %b %Y"),"%e %b %Y")

